from django.db import models

CART_SUBTOTAL_DECIMAL_PLACES = 2
CART_SUBTOTAL_MAX_DIGITS = 10
CART_SUBTOTAL_DEFAULT = 0

PRODUCT_NAME_MAX_LENGTH = 50
PRODUCT_CATEGORY_MAX_LENGTH = 25

PRODUCT_BASE_PRICE_MAX_DIGITS = 5
PRODUCT_BASE_PRICE_DECIMAL_PLACES = 2
PRODUCT_BASE_PRICE_MIN_VALUE = 1
PRODUCT_DISCOUNT_PERCENTAGE_DEFAULT_VALUE = 0
PRODUCT_DISCOUNT_PERCENTAGE_MIN_VALUE = 0
PRODUCT_DISCOUNT_PERCENTAGE_MAX_VALUE = 100
PRODUCT_IMAGE_UPLOAD_DIRECTORY = 'products/'

class Categories(models.TextChoices):
    SALAD = 'Salad', 'Salad'
    PIZZA = 'Pizza', 'Pizza'
    SUSHI = 'Sushi', 'Sushi'
    GRILL = 'Grill', 'Grill'
    BURGER = 'Burger', 'Burger'
    PASTA = 'Pasta', 'Pasta'
    DESSERT = 'Dessert', 'Dessert'
    DRINK = 'Drink', 'Drink'